Output an informative message on health check fail.

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -30,6 +30,7 @@ curl="curl -sS \
 function alive_or_exit {
     # shellcheck disable=SC2068
     if [[ $($@) != "Tackar som frågar!"* ]]; then
+        >&2 echo "Health check failed :("
         exit 1
     fi
 }
